"""Write a review table of every translated text: English, Dutch and Hungarian side by side, and where it appears.

Run with `.venv\\Scripts\\python tools\\translation_review.py <output.md>`. Corrections go into blocky/language.py (and
the date tables in blocky/clock.py); then run this again instead of editing the table by hand.
"""

import ast
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from blocky import clock, language  # noqa: E402
from blocky.clock import TimeStyle  # noqa: E402

MARKERS = ("_", "translate", "marked", "shown")


def keys_and_places() -> dict[str, list[str]]:
    """Each table key used in the code, with the file and line of every use, in the order they first appear."""
    places: dict[str, list[str]] = {}
    for path in sorted((ROOT / "blocky").glob("*.py")):
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not isinstance(node, ast.Call) or not node.args:
                continue
            name = node.func.id if isinstance(node.func, ast.Name) else getattr(node.func, "attr", None)
            first = node.args[0]
            if name not in MARKERS or not isinstance(first, ast.Constant) or not isinstance(first.value, str):
                continue
            context = next((k.value for k in node.keywords if k.arg == "context"), None)
            key = first.value
            if isinstance(context, ast.Constant) and isinstance(context.value, str) and context.value:
                key = f"{context.value}|{key}"
            places.setdefault(key, []).append(f"{path.name}:{node.lineno}")
    return places


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def main(output: Path) -> None:
    places = keys_and_places()
    lines = [
        "# Translations for review",
        "",
        "Generated by `tools/translation_review.py`; do not edit by hand. Corrections go into `blocky/language.py`.",
        "`{name}` parts are filled in by Blocky. A key such as `event|Override` is the History event name, which",
        "other languages word differently from the Override button.",
        "",
        "| # | English | Dutch | Hungarian | Where |",
        "|---|---|---|---|---|",
    ]
    for number, key in enumerate(sorted(places, key=lambda key: places[key][0]), start=1):
        english = key.split("|", 1)[1] if "|" in key else key
        shown_key = f"({key.split('|', 1)[0]}) {english}" if "|" in key else english
        dutch, hungarian = language.NL.get(key, "**missing**"), language.HU.get(key, "**missing**")
        lines.append(f"| {number} | {cell(shown_key)} | {cell(dutch)} | {cell(hungarian)} | {', '.join(places[key])} |")

    moment = datetime(2026, 10, 4, 17, 5)
    lines += ["", "## Dates, days and times", "", "| | English | Dutch | Hungarian |", "|---|---|---|---|"]
    rows = {
        "Short day names": lambda code: ", ".join(clock.SHORT_DAYS[code]),
        "Full day names": lambda code: ", ".join(clock.FULL_DAYS[code]),
        "Short month names": lambda code: ", ".join(clock.MONTHS[code]),
        "History date, 24-hour": lambda code: clock.format_date(moment, TimeStyle(language=code)),
        "History date, 12-hour": lambda code: clock.format_date(moment, TimeStyle(twelve_hour=True, language=code)),
        "Midnight and noon, 12-hour": lambda code: " / ".join(
            clock.format_time(hour, 0, TimeStyle(twelve_hour=True, language=code)) for hour in (0, 12)
        ),
        "Duration": lambda code: clock.format_duration(125, code),
        "Schedule": lambda code: clock.describe_schedule([0, 1, 2, 3, 4], "09:00", "17:00", TimeStyle(language=code)),
    }
    for title, make in rows.items():
        lines.append(f"| {title} | " + " | ".join(cell(make(code)) for code in language.LANGUAGES) + " |")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(places)} texts written to {output}")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
